[2024-06-30T15:50:15.976+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T15:50:16.028+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insee_td_integration.dynamic_tasks_creation manual__2024-06-30T15:50:12.898122+02:00 [queued]>
[2024-06-30T15:50:16.040+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insee_td_integration.dynamic_tasks_creation manual__2024-06-30T15:50:12.898122+02:00 [queued]>
[2024-06-30T15:50:16.041+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-30T15:50:16.137+0200] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dynamic_tasks_creation> on 2024-06-30 15:50:12.898122+02:00
[2024-06-30T15:50:16.145+0200] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-30T15:50:16.147+0200] {standard_task_runner.py:63} INFO - Started process 84 to run task
[2024-06-30T15:50:16.148+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'insee_td_integration', 'dynamic_tasks_creation', 'manual__2024-06-30T15:50:12.898122+02:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/insee_td_integration.py', '--cfg-path', '/tmp/tmp7wmghuzb']
[2024-06-30T15:50:16.149+0200] {standard_task_runner.py:91} INFO - Job 123: Subtask dynamic_tasks_creation
[2024-06-30T15:50:16.259+0200] {task_command.py:426} INFO - Running <TaskInstance: insee_td_integration.dynamic_tasks_creation manual__2024-06-30T15:50:12.898122+02:00 [running]> on host 8d04a427e03d
[2024-06-30T15:50:16.455+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='insee_td_integration' AIRFLOW_CTX_TASK_ID='dynamic_tasks_creation' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T15:50:12.898122+02:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-30T15:50:12.898122+02:00'
[2024-06-30T15:50:16.457+0200] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T15:50:16.457+0200] {logging_mixin.py:188} INFO - Files found: ['/opt/airflow/upload/insee/td/BTT_TD_POP1A_2006.txt']
[2024-06-30T15:50:16.458+0200] {python.py:237} INFO - Done. Returned value was: [<Task(PythonOperator): process_BTT_TD_POP1A_2006.txt>]
[2024-06-30T15:50:16.459+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T15:50:16.476+0200] {xcom.py:675} ERROR - Object of type PythonOperator is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2024-06-30T15:50:16.478+0200] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'airflow.operators.python.PythonOperator'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PythonOperator is not JSON serializable
[2024-06-30T15:50:16.496+0200] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=insee_td_integration, task_id=dynamic_tasks_creation, run_id=manual__2024-06-30T15:50:12.898122+02:00, execution_date=20240630T155012, start_date=20240630T155016, end_date=20240630T155016
[2024-06-30T15:50:16.539+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 123 for task dynamic_tasks_creation (Object of type PythonOperator is not JSON serializable; 84)
[2024-06-30T15:50:16.563+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-30T15:50:16.598+0200] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T15:50:16.616+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
