[2024-06-30T16:12:04.016+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T16:12:04.042+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insee_td_integration.dynamic_tasks_creation manual__2024-06-30T16:06:56.710966+02:00 [queued]>
[2024-06-30T16:12:04.052+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insee_td_integration.dynamic_tasks_creation manual__2024-06-30T16:06:56.710966+02:00 [queued]>
[2024-06-30T16:12:04.053+0200] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-30T16:12:04.085+0200] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dynamic_tasks_creation> on 2024-06-30 16:06:56.710966+02:00
[2024-06-30T16:12:04.098+0200] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-30T16:12:04.099+0200] {standard_task_runner.py:63} INFO - Started process 171 to run task
[2024-06-30T16:12:04.100+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'insee_td_integration', 'dynamic_tasks_creation', 'manual__2024-06-30T16:06:56.710966+02:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/insee_td_integration.py', '--cfg-path', '/tmp/tmp5ymreb6f']
[2024-06-30T16:12:04.101+0200] {standard_task_runner.py:91} INFO - Job 132: Subtask dynamic_tasks_creation
[2024-06-30T16:12:04.180+0200] {task_command.py:426} INFO - Running <TaskInstance: insee_td_integration.dynamic_tasks_creation manual__2024-06-30T16:06:56.710966+02:00 [running]> on host 8c2efe95be8f
[2024-06-30T16:12:04.331+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='insee_td_integration' AIRFLOW_CTX_TASK_ID='dynamic_tasks_creation' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T16:06:56.710966+02:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-30T16:06:56.710966+02:00'
[2024-06-30T16:12:04.332+0200] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T16:12:04.333+0200] {logging_mixin.py:188} INFO - [CREATE_TASK] Files found: ['/opt/airflow/upload/insee/td/BTT_TD_POP1A_2006.txt']
[2024-06-30T16:12:04.333+0200] {python.py:237} INFO - Done. Returned value was: [<Task(PythonOperator): process_BTT_TD_POP1A_2006.txt>]
[2024-06-30T16:12:04.333+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T16:12:04.345+0200] {xcom.py:675} ERROR - Object of type PythonOperator is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2024-06-30T16:12:04.347+0200] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'airflow.operators.python.PythonOperator'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PythonOperator is not JSON serializable
[2024-06-30T16:12:04.360+0200] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=insee_td_integration, task_id=dynamic_tasks_creation, run_id=manual__2024-06-30T16:06:56.710966+02:00, execution_date=20240630T160656, start_date=20240630T161204, end_date=20240630T161204
[2024-06-30T16:12:04.392+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 132 for task dynamic_tasks_creation (Object of type PythonOperator is not JSON serializable; 171)
[2024-06-30T16:12:04.434+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-30T16:12:04.461+0200] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T16:12:04.486+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
